<a href="https://colab.research.google.com/github/Sagar122198/ML/blob/main/Applying_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from collections import Counter

In [ ]:
def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((np.array(point1) - np.array(point2))**2))

In [ ]:
def knn_predict(training_data, training_labels, test_point, k):
    distances = []
    for i in range(len(training_data)):
        dist = euclidean_distance(test_point, training_data[i])
        distances.append((dist, training_labels[i]))
    distances.sort(key=lambda x: x[0])
    k_nearest_labels = [label for _, label in distances[:k]]
    return Counter(k_nearest_labels).most_common(1)[0][0]

In [ ]:
training_data = [[1, 2], [2, 3], [3, 4], [6, 7], [7, 8]]
training_labels = ['A', 'A', 'A', 'B', 'B']
test_point = [4, 5]
k = 3

In [ ]:
prediction = knn_predict(training_data, training_labels, test_point, k)
print(prediction)

A

In [ ]:
import pandas as pd
df = pd.read_csv('student_placement.csv')
display(df.head())
df.info()

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed,0.00
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed,0.00
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed,0.00
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed,12.16

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   student_id                 100000 non-null  int64
 1   age                        100000 non-null  int64
 2   gender                     100000 non-null  object
 3   cgpa                       100000 non-null  float64
 4   branch                     100000 non-null  object
 5   college_tier               100000 non-null  object
 6   internships_count          100000 non-null  int64
 7   projects_count             100000 non-null  int64
 8   certifications_count       100000 non-null  int64
 9   coding_skill_score         100000 non-null  float64
 10  aptitude_score             100000 non-null  float64
 11  communication_skill_score  100000 non-null  float64
 12  logical_reasoning_score    100000 non-null  float64
 13  hackathons_participated    100000 non-null  int64
 14  github_repos               100000 non-null  int64
 15  linkedin_connections       100000 non-null  int64
 16  mock_interview_score       100000 non-null  float64
 17  attendance_percentage      100000 non-null  float64
 18  backlogs                   100000 non-null  int64
 19  extracurricular_score      100000 non-null  float64
 20  leadership_score           100000 non-null  float64
 21  volunteer_experience       100000 non-null  object
 22  sleep_hours                100000 non-null  float64
 23  study_hours_per_day        100000 non-null  float64
 24  placement_status           100000 non-null  object
 25  salary_package_lpa         100000 non-null  float64
dtypes: float64(12), int64(9), object(5)
memory usage: 19.8+ MB

In [ ]:
# Separate features (X) and target (y)
X = df.drop('placement_status', axis=1)
y = df['placement_status']

# Identify categorical columns for one-hot encoding
categorical_cols = X.select_dtypes(include=['object']).columns

# Apply one-hot encoding to categorical features
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

display(X.head())
X.info()

,student_id,age,cgpa,internships_count,projects_count,certifications_count,coding_skill_score,aptitude_score,communication_skill_score,logical_reasoning_score,...,salary_package_lpa,gender_Male,branch_Civil,branch_ECE,branch_EEE,branch_IT,branch_Mechanical,college_tier_Tier 2,college_tier_Tier 3,volunteer_experience_Yes
0,1,24,7.53,4,6,1,99.238568,81.707722,57.707166,59.070073,...,0.00,True,False,False,False,True,False,True,False,True
1,2,21,7.92,1,3,6,80.966123,63.116715,59.197085,78.976419,...,0.00,True,False,False,False,False,False,True,False,False
2,3,22,8.60,0,1,1,49.177184,48.658753,92.104885,80.603331,...,11.99,False,False,False,True,False,False,False,False,False
3,4,24,6.68,0,2,2,79.359084,66.376653,83.411798,64.187246,...,0.00,True,False,False,False,False,False,False,False,True
4,5,20,8.43,1,4,3,65.018573,61.274985,88.956331,56.163678,...,12.16,False,False,False,False,True,False,False,True,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 30 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   student_id                 100000 non-null  int64
 1   age                        100000 non-null  int64
 2   cgpa                       100000 non-null  float64
 3   internships_count          100000 non-null  int64
 4   projects_count             100000 non-null  int64
 5   certifications_count       100000 non-null  int64
 6   coding_skill_score         100000 non-null  float64
 7   aptitude_score             100000 non-null  float64
 8   communication_skill_score  100000 non-null  float64
 9   logical_reasoning_score    100000 non-null  float64
 10  hackathons_participated    100000 non-null  int64
 11  github_repos               100000 non-null  int64
 12  linkedin_connections       100000 non-null  int64
 13  mock_interview_score       100000 non-null  float64
 14  attendance_percentage      100000 non-null  float64
 15  backlogs                   100000 non-null  int64
 16  extracurricular_score      100000 non-null  float64
 17  leadership_score           100000 non-null  float64
 18  sleep_hours                100000 non-null  float64
 19  study_hours_per_day        100000 non-null  float64
 20  salary_package_lpa         100000 non-null  float64
 21  gender_Male                100000 non-null  bool
 22  branch_Civil               100000 non-null  bool
 23  branch_ECE                 100000 non-null  bool
 24  branch_EEE                 100000 non-null  bool
 25  branch_IT                  100000 non-null  bool
 26  branch_Mechanical          100000 non-null  bool
 27  college_tier_Tier 2        100000 non-null  bool
 28  college_tier_Tier 3        100000 non-null  bool
 29  volunteer_experience_Yes   100000 non-null  bool
dtypes: bool(9), float64(12), int64(9)
memory usage: 16.9 MB

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and apply StandardScaler to scale numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Shape of X_train_scaled: {X_train_scaled.shape}")
print(f"Shape of X_test_scaled: {X_test_scaled.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train_scaled: (70000, 30)
Shape of X_test_scaled: (30000, 30)
Shape of y_train: (70000,)
Shape of y_test: (30000,)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize the KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)  # You can adjust n_neighbors

# Train the model on the scaled training data
knn.fit(X_train_scaled, y_train)

# Make predictions on the scaled test data
y_pred = knn.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9799

Classification Report:
              precision    recall  f1-score   support

  Not Placed       0.98      0.97      0.98     13750
      Placed       0.98      0.98      0.98     16250

    accuracy                           0.98     30000
   macro avg       0.98      0.98      0.98     30000
weighted avg       0.98      0.98      0.98     30000